language: python

python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.9-dev"
  - "pypy3"


before_install:
- pip install poetry

install:
- poetry install
- pip install -r requirements.txt
- pip install coverage

script:
  - coverage run --source=rekishikon --omit=rekishikon/tests/* -m unittest discover

after_success:
- bash <(curl -s https://codecov.io/bash)

after_script:
 - coverage report
 - pip install pep8 pyflakes
 - pyflakes .| tee >(wc -l)
 - pep8 --statistics --count .